homepage/urls.py
from django.urls import path
from .views import HomePage, Result, DetailView

app_name = 'homepage'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('result/', Result.as_view(), name='result'),
    path('result/<int:pk>/', DetailView.as_view(), name='detail'),
]

lesson_14/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
]

homepage/models.py
from django.db import models
import datetime

__all__ = {'File'}


class File(models.Model):
    id_file: str = models.CharField(max_length=30, null=False, blank=False, help_text='ID File', verbose_name='ID File')
    title_file: str = models.CharField(max_length=30, null=False, blank=False, help_text='Title File',
                                       verbose_name='Title File')
    upload_date: datetime.datetime = models.DateTimeField(auto_now_add=True, help_text='Date Upload',
                                                          verbose_name='Date Upload')
    content_file: str = models.TextField(help_text='Content File', verbose_name='Content File')
    result_analysis: str = models.TextField(help_text='Result Analysis', verbose_name='Result Analysis')

    def __str__(self) -> str:
        return self.id_file

homepage/views.py
import json
from collections import Counter

from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views import generic
from django.views.generic.base import View

from homepage.models import File

__all__ = {'HomePage', 'Result', 'DetailView'}


class HomePage(View):
    @staticmethod
    def get(request: HttpRequest) -> HttpResponse:
        return render(request, 'homepage/index.html')


class Result(View):
    @staticmethod
    def get(request: HttpRequest) -> HttpResponse:
        get_last_5_files = File.objects.order_by('-upload_date')[:5]

        context = dict(last_5_files=get_last_5_files)

        return render(request, 'homepage/result.html', context)

    def post(self, request: HttpRequest) -> HttpResponse:
        id_file = request.POST['id_file']

        try:
            File.objects.get(id_file=id_file)
            messages.error(request, 'Error: this ID already exists!')
            return render(request, 'homepage/index.html')
        except ObjectDoesNotExist:
            title_file = request.POST['title_file']
            content = self._handle_uploaded_file(request.FILES['file'], title_file)
            result_analysis_text = dict(Counter(content.split()))
            content_file_in_json = json.dumps(content)

            object_file = File(id_file=id_file, title_file=title_file, content_file=content_file_in_json,
                               result_analysis=result_analysis_text)
            object_file.save()

            get_last_5_files = File.objects.order_by('-upload_date')[:5]

            context = dict(last_5_files=get_last_5_files)

            return render(request, 'homepage/result.html', context)

    @staticmethod
    def _handle_uploaded_file(f: InMemoryUploadedFile, file_name: str) -> str:
        with open(f'files/{file_name}.txt', 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
        file_json = open(f'files/{file_name}.txt')
        content_in_file = file_json.read()
        file_json.close()
        return content_in_file


class DetailView(generic.DetailView):
    model = File
    template_name = 'homepage/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        result_in_str = File.objects.get(id_file=context['file']).result_analysis
        result_in_str = result_in_str.replace('\'', '\"')
        context['result_analysis'] = json.loads(result_in_str)
        return context

templates/homepage/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail File №{{ file.id }}</title>
</head>
<body>
<table width="25%" border="1" cellspacing="0" cellpadding="4">
    <caption><h2>Detail File №{{ file.id }}:</h2></caption>
    <tr>
        <th>Letter</th>
        <th>Count</th>
    </tr>
    {% for key, value in result_analysis.items %}
        <tr>
            <td>{{ key }}</td>
            <td>{{ value }}</td>
        </tr>
    {% endfor %}
</table>
<p><a href="{% url 'homepage:home' %}">Return to Home Page</a></p>
</body>
</html>

templates/homepage/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
<form action="{% url 'homepage:result' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="id_file" placeholder="ID File">
    <input type="text" name="title_file" placeholder="Title File">
    <label for="file">Choose file to upload</label>
    <input type="file" id="file" name="file" accept=".txt">
    <p><input type="submit" value="Upload File"></p>
</form>
{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}
<p><a href="{% url 'homepage:result' %}">Go to Result Page</a></p>
</body>
</html>

templates/homepage/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result Upload</title>
</head>
<body>
<h2>5 last uploaded files: </h2>
{% for file in last_5_files %}
    <li>Title: {{ file.title_file }}, Upload: {{ file.upload_date }}, <a href="{% url 'homepage:detail' file.id %}">Result
        Analisys File --></a>
    </li>
{% endfor %}
<p><a href="{% url 'homepage:home' %}">Return to Home Page</a></p>
</body>
</html>